version: '3.8'

services:
  # Main API service
  auth-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: auth-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - rabbitmq
      - redis

  # Email worker service
  email-worker:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: email-worker
    command: node src/workers/email.worker.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - rabbitmq
      - redis

  # Redis
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"   # host 5673 → container 5672
      - "15673:15672" # management UI host 15673 → container 15672

volumes:
  pg_data:
